sudo: false

language: python

python:
  - "3.5"
  - "3.6"

services:
  - redis-server

install:
  - pip install -e .[tests] isort unify flake8
  - pip freeze

script:
  - pytest
  - flake8
  - isort --check-only --diff --recursive channels_redis tests
  - unify --check-only --recursive --quote \" channels_redis tests

jobs:
  include:
    - stage: release
      python: "3.6"
      services: []
      install: skip
      script: skip
      deploy:
        provider: pypi
        user: genialis-bot
        password:
          secure: "S9PkHiWOmJbtxYCfKvBc4ytjNk+GWBGa1fO6QnCgKG3O1GX5jA8cso2W/HvmriGbPhv34dD99da70e7uxByO1gfiIvzV4tQTs0tCcgxwCU7kxDaYAlMr9UeuMSBbh1Vyb4ycSmwRtQzCWwwvgvFya0BHw5c4Cg6KdzSJl7OvjohrEE8tLwutnjhk2u6CzA5CTWkfGVjZYSxiaR1A1oHJLYjbzaEAjW2TipToveiv/kK4vh3FdH/K4RjkgPfLrCscyRAB8W4mCD7feL+WvqgnNndn8TypFpM8OeF/ypRWFdgUqc4gsSbzr9cdqpqxUaVgJR0OLh0o2bujziqmns6rKSuPyqRG7ZJCBi7ZXfnqmamSumQfggPZQLwovfwXjPx6QBJRYr91TJqPZm4eSxp21e97LT7SKJ4RoKlrrFBh7xfsPM4EZgXV4fJwYrakKKPv9s3T2+NJBtYLOe0T+k8lFaj0p2dfl0STD0teJ19lDDU0LZnubJWuWUrm6bCSzZ3Of7JJpB3Z/mZf4otIrbB9YjyYL7bQSUbfcXRmbBvyiUKOufRraA7syX5MI6YVpm+9FPBB4ILq47YjMB2El2iYKZGJRGZjpmMd+jUIOVT2ON4JxesZ8Vu0YZKHIQb7ixBiXkrO5f3tA8SSmz4+jY9BsjEMsPe61Kh+KFQTP9CCC5s="
        on:
          tags: true
        distributions: sdist bdist_wheel
