sudo: false

language: python

python:
  - "3.5"
  - "3.6"

services:
  - redis-server

install:
  - pip install -e .[tests] isort unify flake8
  - pip freeze

script:
  - pytest
  - flake8
  - isort --check-only --diff --recursive channels_redis tests
  - unify --check-only --recursive --quote \" channels_redis tests
